application: sodium-pathway-93914
version: 1
runtime: php55
api_version: 1
module: default

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts
  
- url: /student
  static_dir: student

- url: /
  script: index.html
  
- url: /register
  script: register.php

- url: /login
  script: login.php
  
- url: /test-login
  script: test-login.php
  
- url: /test-register
  script: test-register.php

- url: /panel\.html
  script: panel.html
  
- url: /panel-nav\.html
  script: panel-nav.html
  
- url: /add-lesson
  script: add-lesson.php
  
- url: /lessons
  script: lessons.php
  
- url: /get-lesson
  script: get-lesson.php
  
- url: /example
  script: example.json